### ISSUE TITLE
No function switch launch

### ISSUE THREAD

**Issue by huynhqin** [Abder-Rahmane/MicroService-FastAPI-VSCODE#1]
I can not find the MicroService: Switch Launch Mode in visual code
![image](https://github.com/user-attachments/assets/c90f202c-8fa3-4c96-b0b1-a8734f649017)

**Comment by Abder-Rahmane** [comment]
Could you check if you have the latest version, v2.7.5, installed? Then, go to the sidebar, click on the icon FastAPI, you should see "Switch Launch Mode." Refer to the screenshot for further guidance

<img width="418" alt="image" src="https://github.com/user-attachments/assets/100ec139-9a88-4194-b8c0-437824a167c0">

**Comment by Abder-Rahmane** [comment]
Thank you for your feedback! I realized I mistakenly referred to "Switch Launch Mode" as a command when it’s actually just a component in the interface.
